//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuochoanguadua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhmuc_sp
    {
        public int iddm { get; set; }
        public string tendm { get; set; }
        public string hinhanh { get; set; }
        public string ghichu { get; set; }
    }
}
