//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuochoanguadua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donhang
    {
        public int iddh { get; set; }
        public Nullable<int> idtk { get; set; }
        public Nullable<int> idgh { get; set; }
        public string loinhan { get; set; }
        public string ngaygio { get; set; }
        public string hanhchinh { get; set; }
        public string ghichu { get; set; }
    }
}
