//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuochoanguadua.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nuochoa1Entities1 : DbContext
    {
        public nuochoa1Entities1()
            : base("name=nuochoa1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chon> chon { get; set; }
        public virtual DbSet<danhmuc_sp> danhmuc_sp { get; set; }
        public virtual DbSet<donhang> donhang { get; set; }
        public virtual DbSet<giohang> giohang { get; set; }
        public virtual DbSet<san_pham> san_pham { get; set; }
        public virtual DbSet<tk> tk { get; set; }
    }
}
