//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuochoanguadua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class san_pham
    {
        public int idsp { get; set; }
        public Nullable<int> iddm { get; set; }
        public string tensp { get; set; }
        public string giatien { get; set; }
        public string hinhanh { get; set; }
        public string ghichu { get; set; }
    }
}
